Repository opensource-nepal/go-nepali, pull requests merged in 2023-02, with the labels that each got.

#3 Fix install issue
  README.md
  dateConverter/converter_test.go
  go.mod
  nepalitime/nepalitime_test.go
  nepalitime/parser_test.go
  nepalitime/utils.go
  nepalitime/utils_test.go
Labels: bug

#5 Feature: Add method Format() to NepaliTime object
  README.md
  nepalitime/formatter.go
  nepalitime/formatter_test.go
  nepalitime/nepalitime.go
  nepalitime/nepalitime_test.go
Labels: enhancement, unittests

#7 Update README
  README.md
Labels: documentation

#10 Refactored dateConverter code with one single reference point #8
  dateConverter/converter.go
  dateConverter/converter_test.go
Labels: unittests, improvement, refactor
